# Generated by Django 5.2.1 on 2025-05-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('dificultad', models.CharField(max_length=20)),
                ('equipo_necesario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duracion_minutos', models.IntegerField()),
                ('enfoque', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('altura', models.FloatField()),
                ('contrasenia_hash', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgresionEjercicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel_dificultad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.rutinaentrenamiento')),
            ],
        ),
    ]
